const dotenv = require('dotenv');
const axios = require('axios');

dotenv.config();

const isExistCollectionByID = async (apiKey, collectionId) => {
  const response = await axios.get(
    `https://api.getpostman.com/collections/${collectionId}`,
    {
      headers: { 'X-Api-Key': apiKey },
    }
  );
  if (!response.data.collection) {
    console.log('Collection not found');
    throw new Error('Collection not found');
  }
  return response.data.collection;
};

const automatePostman = async (
  apiKey,
  folderName,
  workspaceid,
  collectionName,
  requestsArray
) => {
  if (!Array.isArray(requestsArray)) {
    console.log('requestsArray must be an array');
    throw new Error('requestsArray must be an array');
  }
  const response = await axios.get(
    `https://api.getpostman.com/collections?workspace=${workspaceid}`,
    {
      headers: { 'X-Api-Key': apiKey },
    }
  );

  const allCollections = response.data.collections;

  const existingCollection = allCollections.find(
    collection => collection.name === collectionName
  );
  let collectionId;
  if (existingCollection) {
    collectionId = existingCollection.id;
  } else {
    const collectionResponse = await axios.post(
      'https://api.getpostman.com/collections',
      {
        collection: {
          info: {
            name: collectionName,
            description: 'Requests for my autogenerated API module',
            schema:
              'https://schema.getpostman.com/json/collection/v2.1.0/collection.json',
          },
          item: [],
          workspace: `${workspaceid}`,
          variables: [
            {
              key: 'url',
              value: 'http://localhost:3000',
              type: 'string',
            },
          ],
        },
      },
      {
        headers: { 'X-Api-Key': apiKey },
      }
    );

    collectionId = collectionResponse.data.collection.id;
  }
  const collection = await isExistCollectionByID(apiKey, collectionId);
  const requests = requestsArray.map(request => ({
    name: request.name,
    request: {
      method: request.method,
      url: request.url,

      header: [
        {
          key: 'Authorization',
          value: `Bearer ${request.token || ''}`,
        },
        {
          key: 'Content-Type',
          value: 'application/json', // Set Content-Type to application/json
        },
      ],
      body: {
        mode: 'raw',
        raw: JSON.stringify(request.body, null, 4),
      },
    },
  }));
  const newFolder = {
    name: folderName,
    item: [...collection.item, ...requests],
  };
  collection.item.push(newFolder);

  const updateResponse = await axios.put(
    `https://api.getpostman.com/collections/${collectionId}`,
    {
      collection: {
        ...collection,
      },
    },
    {
      headers: { 'X-Api-Key': apiKey },
    }
  );

  return updateResponse.data;
};

// automatePostman(
//   process.env.POSTMAN_API_KEY,
//   process.env.POSTMAN_FOLDER_NAME,
//   process.env.POSTMAN_WORKSPACE_ID,
//   process.env.POSTMAN_COLLECTION_NAME,
//   [
//     {
//       name: 'Create User',
//       method: 'POST',
//       url: 'https://reqres.in/api/users',
//       token: 'QpwL5tke4Pnpja7X4',
//       body: {
//         name: 'John Doe',
//         job: 'Software Engineer',
//       },
//     },
//     {
//       name: 'Get User',
//       method: 'GET',
//       url: 'https://reqres.in/api/users/2',
//     },
//     {
//       name: 'Update User',
//       method: 'PUT',
//       url: 'https://reqres.in/api/users/2',
//       token: 'QpwL5tke4Pnpja7X4',
//       body: {
//         name: 'John Doe',
//         job: 'Software Engineer',
//       },
//     },
//     {
//       name: 'Delete User',
//       method: 'DELETE',
//       url: 'https://reqres.in/api/users/2',
//       token: 'QpwL5tke4Pnpja7X4',
//     },
//   ]
// ).then(data => console.log(data));
module.exports = { automatePostman };
